apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rdfox.fullname" . }}
  labels:
    {{- include "rdfox.labels" . | nindent 4 }}
data:
  role: {{ .Values.credentials.role | b64enc }}
  password: {{ .Values.credentials.password | b64enc }}
